name: nwm
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - dask
  - dask-core
  - netcdf4
  - numpy
  - pandas
  - pip
  - pytz
  - snakemake-minimal
  - xarray=0.12.2
  - pip:
      git+https://github.com/pydap/pydap.git@master

