name: nwm1
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.7
  - dask
  - dask-core
  - gdal
  - lxml
  - netcdf4
  - numpy
  - pandas
  - pip
  - pytz
  - s3fs
  - snakemake-minimal
  - xarray=0.12.2
  - zarr
  - pip:
      git+https://github.com/pydap/pydap.git

